/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemadecoletadelixo.adminsystem.view;

/**
 *
 * @author Edu
 */
public class FrCadRotas extends javax.swing.JFrame {

    /**
     * Creates new form FrCadRotas
     */
    public FrCadRotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panCad = new javax.swing.JPanel();
        lblPontoInicio = new javax.swing.JLabel();
        lblPontoFim = new javax.swing.JLabel();
        lblRuasPercorridas = new javax.swing.JLabel();
        lblPontosColeta = new javax.swing.JLabel();
        lblSupervisor = new javax.swing.JLabel();
        lblOperadores = new javax.swing.JLabel();
        edtPontoInicio = new javax.swing.JTextField();
        edtSupervisor = new javax.swing.JTextField();
        edtPontoFinalizacao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtOperadores = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        edtPontosColeta = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        edtRuasPercorridas = new javax.swing.JTextArea();
        btnCadastrar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));

        panCad.setMaximumSize(new java.awt.Dimension(1000, 600));
        panCad.setMinimumSize(new java.awt.Dimension(1000, 600));

        lblPontoInicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPontoInicio.setText("Ponto de início:");

        lblPontoFim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPontoFim.setText("Ponto de finalização:");

        lblRuasPercorridas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRuasPercorridas.setText("Ruas Percorridas:");

        lblPontosColeta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPontosColeta.setText("Pontos de coleta:");

        lblSupervisor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSupervisor.setText("Supervisor:");

        lblOperadores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOperadores.setText("Operadores:");

        edtOperadores.setColumns(20);
        edtOperadores.setRows(5);
        jScrollPane1.setViewportView(edtOperadores);

        edtPontosColeta.setColumns(20);
        edtPontosColeta.setRows(5);
        jScrollPane2.setViewportView(edtPontosColeta);

        edtRuasPercorridas.setColumns(20);
        edtRuasPercorridas.setRows(5);
        jScrollPane3.setViewportView(edtRuasPercorridas);

        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panCadLayout = new javax.swing.GroupLayout(panCad);
        panCad.setLayout(panCadLayout);
        panCadLayout.setHorizontalGroup(
            panCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCadLayout.createSequentialGroup()
                .addGroup(panCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCadLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtPontoFinalizacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panCadLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(panCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panCadLayout.createSequentialGroup()
                                .addGroup(panCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRuasPercorridas)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edtSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSupervisor)
                                    .addComponent(edtPontoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPontoInicio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOperadores)
                                    .addComponent(lblPontoFim)
                                    .addComponent(lblPontosColeta)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panCadLayout.createSequentialGroup()
                                .addGap(0, 242, Short.MAX_VALUE)
                                .addComponent(btnCadastrar)
                                .addGap(57, 57, 57)
                                .addComponent(btnVoltar)
                                .addGap(234, 234, 234)))))
                .addGap(86, 86, 86))
        );
        panCadLayout.setVerticalGroup(
            panCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCadLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(panCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPontoInicio)
                    .addComponent(lblPontoFim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtPontoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtPontoFinalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupervisor)
                    .addComponent(lblOperadores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(panCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPontosColeta)
                    .addComponent(lblRuasPercorridas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(panCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnVoltar))
                .addGap(19, 19, 19))
        );

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Sistema de Coleta de Lixo e Recicláveis - Cadastro de Rotas");
        lblTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(panCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(427, Short.MAX_VALUE))
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextArea edtOperadores;
    private javax.swing.JTextField edtPontoFinalizacao;
    private javax.swing.JTextField edtPontoInicio;
    private javax.swing.JTextArea edtPontosColeta;
    private javax.swing.JTextArea edtRuasPercorridas;
    private javax.swing.JTextField edtSupervisor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblOperadores;
    private javax.swing.JLabel lblPontoFim;
    private javax.swing.JLabel lblPontoInicio;
    private javax.swing.JLabel lblPontosColeta;
    private javax.swing.JLabel lblRuasPercorridas;
    private javax.swing.JLabel lblSupervisor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panCad;
    // End of variables declaration//GEN-END:variables
}
